spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa


    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
